DEBUG = TRUE

!IF "$(DEBUG)" == "TRUE"
COPT = /c /W3 /AL /Od /Zip /nologo
LOPT = /CO/NOLOGO/NOE/St:48000
LIBS = GnuLibDR
!ELSE
COPT = /c /W3 /AL /Ox /Grs /Zp /nologo
LOPT = /E/F/PACKC/NOLOGO/NOE/St:48000
LIBS = GnuLibOR
!ENDIF

PROG = regex2

all : $(PROG).exe

$(PROG).obj : $(PROG).c
  cl $(COPT) $*.c

$(PROG).exe : $(PROG).obj
  link $* $(LOPT),,NUL,$(LIBS);
